// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = "https://cpwtwlriwmwgfqgrmfso.supabase.co"
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwd3R3bHJpd213Z2ZxZ3JtZnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1OTcwMzAsImV4cCI6MjA0OTE3MzAzMH0.4dTZ13xDYdGU6YkrNFTGSfPSt_R_hqDCaE9T4aHg6xQ"

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
})