// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

// Prefer runtime env (Vite) when available, fall back to generated defaults.
// This prevents "works locally but not in prod" issues when the Supabase project changes.
const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL || "https://dhjvxtwflntmvbzkqsjn.supabase.co"
const supabaseAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoanZ4dHdmbG50bXZiemtxc2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTY5NjgsImV4cCI6MjA2ODQzMjk2OH0.24FfOJ0xts65leyzQi_rYXPq0LWzCtpSbxz2q2nb1y0"

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
})